[tasks.release-build-service]
env_files = ["../.env"]
command = "cargo"
args = ["build", "--release"]

[tasks.run-service]
env_files = ["../.env.dev"]
command = "cargo"
args = ["run"]

[tasks.build-docker-service]
command = "docker"
args = [
    "build",
    "-t",
    "static:$CARGO_MAKE_CRATE_VERSION",
    "-f",
    "../Dockerfile.service",
    "..",
]
